### ISSUE TITLE
Can't Download Torrents

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/poet#279]
I'm unable to download torrents that are seeded by the production server.

#### Example
https://alpha.po.et/works/88756e12158702f112d914f1ad32f8a914a3b0b1bbd9860d7649ce3b585c7c4e
This work has a torrent hash of `6f2070afc212afef1d22245372b9f437c0acdcaa`, which makes its magnet uri `magnet:?xt=urn:btih:6f2070afc212afef1d22245372b9f437c0acdcaa`.
It's hashed in bitcoin block `1119034`.

My local Po.et node attempts to download that torrent but never starts. (Specifically, WebTorrent never emits any event at all for that `client.add`. See https://webtorrent.io/docs).

Also tried downloading that torrent with https://instant.io/ to no avail.

TODO: try downloading a torrent hosted in local machine with torrent.io, try in testing environment.

**Comment by lautarodragan** [comment]
Update: built [webtorrent-test](github.com/lautarodragan/webtorrent-test) to reduce the scope of the issue. I'm facing the same issue in this small experiment.

The downloader code seems to work well. The following tests run smoothly:
- `node downloader.js 08ada5a7a6183aae1e09d831df6748d566095a10`, which is the demo movie provided by WebTorrent
- Seeding a file from instant.io and downloading it with `node downloader.js`

Progress on seeding:
- Seeding a local text file and downloading it from instant.io: instant.io connects and retrieves the torrent's data. seeder.js shows that it has one peer. But the download never starts. Downloading the .torrent file generated by instant.io and using it with Transmission BitTorrent Client never starts the download either.

**Comment by pmosse** [comment]
Update on my current status:

- I was able to seed a file with instant.io and download it locally with downloader.js.
- I was not able to seed a file locally and download it locally too, even when connected directly to my modem (through ethernet).
- I am now running both the seeder and the downloader in my machine, with a local instance of webtorrent (with npm link),  going through the code to see if I can find which ports it uses and/or any point of failure.
